### ISSUE TITLE
PHP Warning when fromCache is true

### ISSUE THREAD

**Issue by eablokker** [Tcheu/craftcms-httprequest#3] opened 2016-06-06 22:27 UTC
ftell() expects parameter 1 to be resource, integer given
craft/app/vendor/guzzle/guzzle/src/Guzzle/Stream/Stream.php(250)

``` twig
{% set header = craft.httpReq.get('https://www.domain.com/', { "pagename" : "Header" }, true) %}
```

Craft CMS 2.6.2789
PHP 5.6.10

**Comment by kant312** [comment] 2016-06-07 09:46
Hi,

I reused the code you provided but I was not able to reproduce the problem (PHP 5.6.0, Craft 2.6.2789). Could it be that there is an issue with the URL you are trying to reach?

**Comment by kant312** [comment] 2016-10-04 09:00
Closing, as I was not able to reproduce the problem.

**Closed as completed by kant312** 2016-10-04 09:00 UTC
